# Generated by Django 3.2.23 on 2024-01-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_t1'),
    ]

    operations = [
        migrations.CreateModel(
            name='T2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t2', models.BigIntegerField()),
            ],
        ),
    ]
