# Generated by Django 3.2.23 on 2024-01-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_t2'),
    ]

    operations = [
        migrations.AddField(
            model_name='t2',
            name='t3',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
