# Generated by Django 3.2.23 on 2024-01-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_t2_t3'),
    ]

    operations = [
        migrations.AddField(
            model_name='t2',
            name='t4',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
